img_size: [120,160]
top_cutoff: 40


colors:
  RED:
    low_1: [0,140,100]
    high_1: [10,255,255]
    low_2: [165,140,100]
    high_2: [180,255,255]

# Sim Settings
#  WHITE:
#    low: [0,0,50]
#    high: [180,110,255]
#  YELLOW:
#    low: [15,110,90]
#    high: [35,255,245]

# IRL Settings
  WHITE:
    low: [10,10,100]
    high: [180,70,255]
  YELLOW:
    low: [5,80,90]
    high: [40,255,245]



# Old Settings
#  WHITE:
#    low: [0,0,50]
#    high: [180,110,255]
#  YELLOW:
#    low: [10,120,100]
#    high: [60,255,255]

line_detector_parameters:
  canny_thresholds: [80,200]
  canny_aperture_size: 3
  dilation_kernel_size: 3
  hough_threshold: 2
  hough_min_line_length: 3
  hough_max_line_gap: 1